version: '3.8'

services:
  app:
    build: .
    container_name: egarden_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./firebase.json:/app/firebase.json

  postgres:
    image: postgres:16
    container_name: egarden_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: